### ISSUE TITLE
포트폴리오 템플릿 찾기

### ISSUE THREAD

**Issue by nawaraing** [NaeDdoCo/nutritional-shopping-mall-web#6]
# 가이드

- 찾은 템플릿 링크를 이 이슈에 코멘트로 공유
- 특별한 사유가 없다면 최종 프로젝트까지 활용할 템플릿 양식

**Comment by Gitkonium** [comment]
[Cordelia · SlidesCarnival.pptx](https://github.com/NaeDdoCo/nutritional-shopping-mall-web/files/14290782/Cordelia.SlidesCarnival.pptx)

PPT 후보 1

**Comment by nawaraing** [comment]
https://www.canva.com/p/templates/EAFQ97nGubU-blue-minimalist-business-pitch-deck-presentation/

**Comment by Gitkonium** [comment]
https://www.slidescarnival.com/salerio-free-presentation-template/1875

**Comment by nawaraing** [comment]
https://www.canva.com/p/templates/EAFCb-2VPNc-white-minimalist-business-chart-presentation/

**Comment by jjeong623** [comment]
https://www.canva.com/design/DAF81sL7NH0/OnmhoO9KC3V0dykVBqIseQ/edit

**Comment by jjeong623** [comment]
https://www.canva.com/p/templates/EAE5XwpL4CE-tosca-green-blue-soft-grey-black-minimalist-thesis-research-study-presentation-template/

**Comment by JeongHoonSeok** [comment]
> https://www.canva.com/p/templates/EAE5XwpL4CE-tosca-green-blue-soft-grey-black-minimalist-thesis-research-study-presentation-template/

굳

**Comment by JeongHoonSeok** [comment]
폰트 : 210 네버랜드
